apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 1m
  releaseName: istio-ingress
  chart:
    spec:
      chart: istio-ingress
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  values:
    gateways:
      enabled: true
      istio-ingressgateway:
        enabled: true
  dependsOn:
    - name: istio-base
    - name: istiod