apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicey
  namespace: servicey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicey
  template:
    metadata:
      labels:
        app: servicey
    spec:
      containers:
      - name: servicey
        image: hamidhirsi/s2s:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/kpf/enable-config
      volumes:
      - name: config-volume
        configMap:
          name: cleverbit-config
---
apiVersion: v1
kind: Service
metadata:
  name: servicey
  namespace: servicey
spec:
  selector:
    app: servicey
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080